_wandb:
    value:
        cli_version: 0.22.0
        e:
            g0bra28vmndmqllddqvky0ug8rjqbkgd:
                args:
                    - config/train_shakespeare_char.py
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 192
                cpu_count_logical: 384
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "527160320000"
                        used: "145919995904"
                email: hasith@utexas.edu
                executable: /stor/home/vv8379/projects/nanollms/nanoGPT/.venv/bin/python
                git:
                    commit: 93a43d9a5c22450bbf06e78da2cb6eeef084b717
                    remote: https://github.com/karpathy/nanoGPT.git
                gpu: NVIDIA H100 NVL
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-12aa7bb4-da4a-a846-f041-3f0c682e80bb
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-9d1e8b22-42cf-6611-f8b5-4d0599c2a545
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-4f621615-09a9-46b0-524f-6d8e16b12359
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-e9be08a4-1e2f-4147-0f04-3fb6105fba53
                host: gilpcomp01.ccbb.utexas.edu
                memory:
                    total: "811092713472"
                os: Linux-6.14.0-27-generic-x86_64-with-glibc2.39
                program: /stor/home/vv8379/projects/nanollms/nanoGPT/train.py
                python: CPython 3.11.13
                root: /stor/home/vv8379/projects/nanollms/nanoGPT
                startedAt: "2025-09-27T00:18:24.661512Z"
                writerId: g0bra28vmndmqllddqvky0ug8rjqbkgd
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.11.13
            "5": 0.22.0
            "12": 0.22.0
            "13": linux-x86_64
always_save_checkpoint:
    value: false
backend:
    value: nccl
batch_size:
    value: 64
beta1:
    value: 0.9
beta2:
    value: 0.99
bias:
    value: false
block_size:
    value: 256
compile:
    value: true
dataset:
    value: shakespeare_char
decay_lr:
    value: true
device:
    value: cuda
dropout:
    value: 0.2
dtype:
    value: bfloat16
eval_interval:
    value: 250
eval_iters:
    value: 200
eval_only:
    value: false
grad_clip:
    value: 1
gradient_accumulation_steps:
    value: 1
init_from:
    value: scratch
learning_rate:
    value: 0.001
log_interval:
    value: 10
lr_decay_iters:
    value: 5000
max_iters:
    value: 5000
min_lr:
    value: 0.0001
n_embd:
    value: 384
n_head:
    value: 6
n_layer:
    value: 6
out_dir:
    value: out-shakespeare-char
wandb_log:
    value: true
wandb_project:
    value: shakespeare-char
wandb_run_name:
    value: mini-gpt
warmup_iters:
    value: 100
weight_decay:
    value: 0.1
